name: Test
on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sdk-python
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          path: sdk-python

      - name: Checkout integration-test-data
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          repository: quonfig/integration-test-data
          path: integration-test-data
          ref: main

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a  # v1
        with:
          version: "1.8.3"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        working-directory: sdk-python
        run: poetry install --no-interaction

      - name: Lint (ruff)
        working-directory: sdk-python
        run: poetry run ruff check .

      - name: Typecheck (mypy)
        working-directory: sdk-python
        run: poetry run mypy quonfig

      - name: Test
        working-directory: sdk-python
        run: poetry run pytest
